import type { ProviderDefinition } from "./models.js";

/**
 * One entry per provider *type* (not per connected account instance).
 * The Providers tab renders its entire "Add a provider" flow — tiles,
 * dynamic forms, OAuth-vs-API-key branching — from this array. Adding a
 * 15th provider means adding one object here plus its adapter class; no
 * new UI code. See OmniDisk_Provider_Registry_UI_Spec.md §2 for the full
 * design rationale.
 */
export const PROVIDER_REGISTRY: ProviderDefinition[] = [
  {
    providerName: "google_drive",
    displayName: "Google Drive",
    logoUrl: "/logos/google_drive.svg",
    authType: "oauth2",
    freeTierLabel: "15 GB",
    liveQuotaSupported: true,
    isBilledProvider: false,
    setupGuideAnchor: "#1-google-drive",
    appLevelFields: [
      {
        key: "clientId",
        label: "OAuth Client ID",
        type: "text",
        required: true,
        helpText:
          "From Google Cloud Console → Credentials → OAuth client ID (Web application type — add http://127.0.0.1:4310/api/providers/google_drive/oauth-callback as an Authorized redirect URI)",
      },
      { key: "clientSecret", label: "OAuth Client Secret", type: "password", required: true, secret: true },
    ],
    accountLevelFields: [
      { key: "label", label: "Account nickname", type: "text", required: false, placeholder: "e.g. Drive – Personal" },
    ],
    requiresOAuthConnect: true,
  },
  {
    providerName: "onedrive",
    displayName: "OneDrive",
    logoUrl: "/logos/onedrive.svg",
    authType: "oauth2",
    freeTierLabel: "5 GB",
    liveQuotaSupported: true,
    isBilledProvider: false,
    setupGuideAnchor: "#2-onedrive-microsoft-graph",
    appLevelFields: [
      {
        key: "clientId",
        label: "Application (client) ID",
        type: "text",
        required: true,
        helpText: "From Microsoft Entra ID → App registrations",
      },
      {
        key: "tenantId",
        label: "Tenant ID",
        type: "text",
        required: false,
        default: "common",
        helpText: "Use 'common' to allow both personal and work/school accounts",
      },
    ],
    accountLevelFields: [{ key: "label", label: "Account nickname", type: "text", required: false }],
    requiresOAuthConnect: true,
  },
  {
    providerName: "dropbox",
    displayName: "Dropbox",
    logoUrl: "/logos/dropbox.svg",
    authType: "oauth2",
    freeTierLabel: "~2 GB",
    liveQuotaSupported: true,
    maxSingleObjectBytes: 150_000_000,
    isBilledProvider: false,
    setupGuideAnchor: "#3-dropbox",
    appLevelFields: [
      { key: "appKey", label: "App Key", type: "text", required: true, helpText: "From dropbox.com/developers/apps" },
      { key: "appSecret", label: "App Secret", type: "password", required: true, secret: true },
    ],
    accountLevelFields: [{ key: "label", label: "Account nickname", type: "text", required: false }],
    requiresOAuthConnect: true,
  },
  {
    providerName: "box",
    displayName: "Box",
    logoUrl: "/logos/box.svg",
    authType: "oauth2",
    freeTierLabel: "10 GB (Individual plan)",
    liveQuotaSupported: true,
    maxSingleObjectBytes: 250_000_000,
    isBilledProvider: false,
    setupGuideAnchor: "#4-box",
    appLevelFields: [
      {
        key: "clientId",
        label: "Client ID",
        type: "text",
        required: true,
        helpText:
          "Box's free plan is Individual, not Business — credentials live in the Developer Console (app.box.com/developers/console → My Apps → Create Platform App → Custom App → User Authentication (OAuth 2.0)), which is a completely separate area from the regular Box web app and easy to miss.",
      },
      { key: "clientSecret", label: "Client Secret", type: "password", required: true, secret: true },
    ],
    accountLevelFields: [{ key: "label", label: "Account nickname", type: "text", required: false }],
    requiresOAuthConnect: true,
  },
  {
    providerName: "pcloud",
    displayName: "pCloud",
    logoUrl: "/logos/pcloud.svg",
    authType: "oauth2",
    freeTierLabel: "2 GB at signup (up to 10 GB via referrals/tasks)",
    liveQuotaSupported: true,
    isBilledProvider: false,
    setupGuideAnchor: "#5-pcloud",
    appLevelFields: [
      { key: "clientId", label: "Client ID", type: "text", required: true },
      { key: "clientSecret", label: "Client Secret", type: "password", required: true, secret: true },
    ],
    accountLevelFields: [
      { key: "label", label: "Account nickname", type: "text", required: false },
      {
        key: "region",
        label: "Data region",
        type: "select",
        required: true,
        options: [
          { value: "us", label: "US (api.pcloud.com)" },
          { value: "eu", label: "EU (eapi.pcloud.com)" },
        ],
        helpText: "Must match the region your pCloud account was created in",
      },
    ],
    requiresOAuthConnect: true,
  },
  {
    providerName: "mega",
    displayName: "MEGA",
    logoUrl: "/logos/mega.svg",
    authType: "basic",
    freeTierLabel: "~20 GB",
    liveQuotaSupported: true,
    isBilledProvider: false,
    setupGuideAnchor: "#6-mega",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Account nickname", type: "text", required: false },
      { key: "email", label: "MEGA account email", type: "text", required: true },
      { key: "password", label: "MEGA account password", type: "password", required: true, secret: true },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "github",
    displayName: "GitHub",
    logoUrl: "/logos/github.svg",
    authType: "api_key",
    freeTierLabel: "Soft cap (repo-based)",
    liveQuotaSupported: false,
    maxSingleObjectBytes: 90_000_000,
    isBilledProvider: false,
    setupGuideAnchor: "#7-github-repo-based-storage",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      {
        key: "personalAccessToken",
        label: "Fine-grained PAT",
        type: "password",
        required: true,
        secret: true,
        helpText: "Scope: Contents Read & write, restricted to one dedicated repo",
      },
      { key: "owner", label: "Repo owner", type: "text", required: true },
      { key: "repo", label: "Repo name", type: "text", required: true },
      {
        key: "freeSpaceCapGB",
        label: "Configured capacity (GB)",
        type: "number",
        required: true,
        default: 2,
        helpText: "GitHub has no live quota API — set a soft ceiling you're comfortable with",
      },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "gitlab",
    displayName: "GitLab",
    logoUrl: "/logos/gitlab.svg",
    authType: "api_key",
    freeTierLabel: "Soft cap (package registry)",
    liveQuotaSupported: false,
    isBilledProvider: false,
    setupGuideAnchor: "#8-gitlab-repopackage-based-storage",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      { key: "personalAccessToken", label: "Personal Access Token", type: "password", required: true, secret: true },
      { key: "projectId", label: "Project ID", type: "text", required: true },
      { key: "freeSpaceCapGB", label: "Configured capacity (GB)", type: "number", required: true, default: 5 },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "cloudflare_r2",
    displayName: "Cloudflare R2",
    logoUrl: "/logos/r2.svg",
    authType: "api_key",
    freeTierLabel: "10 GB",
    liveQuotaSupported: false,
    isBilledProvider: false,
    setupGuideAnchor: "#9-cloudflare-r2-s3-compatible",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      { key: "accountId", label: "Cloudflare Account ID", type: "text", required: true },
      { key: "accessKeyId", label: "Access Key ID", type: "text", required: true },
      { key: "secretAccessKey", label: "Secret Access Key", type: "password", required: true, secret: true },
      { key: "bucket", label: "Bucket name", type: "text", required: true },
      { key: "freeSpaceCapGB", label: "Configured capacity (GB)", type: "number", required: true, default: 10 },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "backblaze_b2",
    displayName: "Backblaze B2",
    logoUrl: "/logos/b2.svg",
    authType: "api_key",
    freeTierLabel: "10 GB",
    liveQuotaSupported: false,
    isBilledProvider: false,
    setupGuideAnchor: "#10-backblaze-b2",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      {
        key: "keyId",
        label: "Application Key ID",
        type: "text",
        required: true,
        helpText: "Must be a manually-created key, not the auto-generated master key",
      },
      { key: "applicationKey", label: "Application Key", type: "password", required: true, secret: true },
      { key: "bucket", label: "Bucket name", type: "text", required: true },
      {
        key: "endpoint",
        label: "S3 endpoint",
        type: "url",
        required: true,
        placeholder: "https://s3.us-west-004.backblazeb2.com",
      },
      { key: "freeSpaceCapGB", label: "Configured capacity (GB)", type: "number", required: true, default: 10 },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "s3",
    displayName: "Amazon S3",
    logoUrl: "/logos/s3.svg",
    authType: "api_key",
    freeTierLabel: "Billed (12-mo free tier only for new accounts)",
    liveQuotaSupported: false,
    isBilledProvider: true,
    setupGuideAnchor: "#11-amazon-s3",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      { key: "accessKeyId", label: "Access Key ID", type: "text", required: true },
      { key: "secretAccessKey", label: "Secret Access Key", type: "password", required: true, secret: true },
      { key: "region", label: "Region", type: "text", required: true, placeholder: "us-east-1" },
      { key: "bucket", label: "Bucket name", type: "text", required: true },
      { key: "spendingCapGB", label: "Spending-conscious cap (GB)", type: "number", required: true },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "azure_blob",
    displayName: "Azure Blob Storage",
    logoUrl: "/logos/azure.svg",
    authType: "api_key",
    freeTierLabel: "Billed (trial credit only)",
    liveQuotaSupported: false,
    isBilledProvider: true,
    setupGuideAnchor: "#12-azure-blob-storage",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      {
        key: "connectionStringOrSas",
        label: "Connection string / SAS token",
        type: "password",
        required: true,
        secret: true,
      },
      { key: "containerName", label: "Container name", type: "text", required: true },
      { key: "spendingCapGB", label: "Spending-conscious cap (GB)", type: "number", required: true },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "gcs",
    displayName: "Google Cloud Storage",
    logoUrl: "/logos/gcs.svg",
    authType: "api_key",
    freeTierLabel: "Billed (small Always Free tier)",
    liveQuotaSupported: false,
    isBilledProvider: true,
    setupGuideAnchor: "#13-google-cloud-storage-gcs",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      { key: "serviceAccountJson", label: "Service account JSON key", type: "password", required: true, secret: true },
      { key: "bucket", label: "Bucket name", type: "text", required: true },
      { key: "spendingCapGB", label: "Spending-conscious cap (GB)", type: "number", required: true },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "webdav",
    displayName: "WebDAV",
    logoUrl: "/logos/webdav.svg",
    authType: "basic",
    freeTierLabel: "Depends on server",
    liveQuotaSupported: false,
    isBilledProvider: false,
    setupGuideAnchor: "#14-webdav-generic-provider",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      { key: "baseUrl", label: "WebDAV base URL", type: "url", required: true },
      { key: "username", label: "Username", type: "text", required: true },
      { key: "password", label: "Password / token", type: "password", required: true, secret: true },
      {
        key: "freeSpaceCapGB",
        label: "Configured capacity (GB, if server doesn't report quota)",
        type: "number",
        required: false,
      },
    ],
    requiresOAuthConnect: false,
  },
  {
    providerName: "supabase",
    displayName: "Supabase Storage",
    logoUrl: "/logos/supabase.svg",
    authType: "api_key",
    freeTierLabel: "1 GB (50MB max/file; project pauses after 7 days idle)",
    liveQuotaSupported: false,
    maxSingleObjectBytes: 50_000_000,
    isBilledProvider: false,
    setupGuideAnchor: "#15-supabase-storage",
    appLevelFields: [],
    accountLevelFields: [
      { key: "label", label: "Nickname", type: "text", required: false },
      {
        key: "projectUrl",
        label: "Project URL",
        type: "url",
        required: true,
        placeholder: "https://xxxxxxxxxxxx.supabase.co",
        helpText: "Project Settings → Data API → Project URL",
      },
      {
        key: "serviceRoleKey",
        label: "service_role secret key",
        type: "password",
        required: true,
        secret: true,
        helpText:
          "Project Settings → API Keys → service_role (NOT the anon/publishable key — that one can't create buckets or bypass row-level security)",
      },
      {
        key: "freeSpaceCapGB",
        label: "Configured capacity (GB)",
        type: "number",
        required: true,
        default: 1,
        helpText:
          "Supabase's Storage API has no per-bucket quota endpoint, and the 1GB free-tier limit is shared across your whole project (Storage + Database) — set how much of that you want OmniDisk to use",
      },
    ],
    requiresOAuthConnect: false,
  },
];

export function getProviderDefinition(providerName: string): ProviderDefinition | undefined {
  return PROVIDER_REGISTRY.find((p) => p.providerName === providerName);
}
